git:
  remote:
    upstream: 'tychoish/rhizome'
    tools: 'cyborgisntitute/institute-tools'
project:
  name: 'tychoish'
  tag: 'tychoish'
  url: 'http://tychoish.com'
  title: 'tychoish'
  branched: false
  siteroot: true
version:
  release: '0.0.0'
  branch: '0.0'
system:
  make:
    generated:
      - 'meta'
      - 'integration'
      - 'push'
      - 'sphinx'
    static:
      - 'makefile.compatibility'
      - 'makefile.clean'
      - 'makefile.dtf'
  files:
    - 'intersphinx.yaml'
    - 'push.yaml'
    - 'pdfs.yaml'
    - 'sphinx_local.yaml'
    # - images: '/source/images/metadata.yaml'
    # - includes: '/source/includes/metadata.yaml'
assets:
  - branch: master
    path: build/institute-tools
    repository: https://github.com/cyborginstitute/institute-tools.git
  - branch: master
    path: build/docs-tools
    repository: https://github.com/mongodb/docs-tools.git
paths:
  output: 'build'
  source: 'source'
  includes: 'source/includes'
  images: 'source/images'
  tools: 'bin'
  buildsystem: 'build/docs-tools'
  builddata: 'config'
  locale: 'locale'
...