name: python
url: https://docs.python.org/2/
path: python2.inv
---
name: python2
url: https://docs.python.org/2/
path: python2.inv
---
name: python3
url: https://docs.python.org/3/
path: python3.inv
---
name: sphinx
url: http://sphinx-doc.org/
path: sphinx.inv
...
