project: 'tychoish'
master_doc: 'index'
logo: ".static/logo.png"
paths:
  static: ['source/.static']
theme:
  name: 'cyborg'
  project: 'tychoish'
  google_analytics: 'UA-0000000-0'

sidebars:
  '**':
    - 'localtoc.html'
    - 'relations.html'
    # - 'sourcelink.html'
    # - 'postcard.html'
    # - 'recentposts.html'
    # - 'tagcloud.html'
    # - 'categories.html'
    # - 'archives.html'
...