project: 'tychoish'
master_doc: 'index'
logo: ".static/logo.png"
paths:
  static: ['source/.static']
theme:
  name: 'alabaster'
  project: 'tychoish'
  google_analytics: 'UA-2505694-6'
sidebars:
  '**':
    - 'localtoc.html'
    # - 'relations.html'
    - 'postcard.html'
    - 'recentposts.html'
    - 'about.html'
    # - 'tagcloud.html'
    # - 'categories.html'
    - 'archives.html'
    # - 'page_meta.html'
    # - 'gittip.html'
...